/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScopeSuperAdminRouteImport } from './routes/scope-super-admin'
import { Route as ScopeAdminRouteImport } from './routes/scope-admin'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as InstitutionAdminRouteImport } from './routes/institution-admin'
import { Route as InnovationLabRouteImport } from './routes/innovation-lab'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CampusLeaderRouteImport } from './routes/campus-leader'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as BrokenLinkRouteImport } from './routes/broken-link'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AmbassadorRouteImport } from './routes/ambassador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ScopeSuperAdminRbacAuditRouteImport } from './routes/scope-super-admin.rbac-audit'
import { Route as ScopeAdminVisitsRouteImport } from './routes/scope-admin.visits'
import { Route as ScopeAdminReportsRouteImport } from './routes/scope-admin.reports'
import { Route as ScopeAdminMouPipelineRouteImport } from './routes/scope-admin.mou-pipeline'
import { Route as ScopeAdminInstitutionsRouteImport } from './routes/scope-admin.institutions'
import { Route as ScopeAdminDashboardRouteImport } from './routes/scope-admin.dashboard'
import { Route as InstitutionReportsRouteImport } from './routes/institution.reports'
import { Route as InstitutionAdminReportsRouteImport } from './routes/institution-admin.reports'
import { Route as InstitutionAdminMembersRouteImport } from './routes/institution-admin.members'
import { Route as InstitutionAdminCommunicationsRouteImport } from './routes/institution-admin.communications'
import { Route as InstitutionAdminAnalyticsRouteImport } from './routes/institution-admin.analytics'
import { Route as FormsFormSlugRouteImport } from './routes/forms.$formSlug'
import { Route as DevBuildDiagnosticsRouteImport } from './routes/dev.build-diagnostics'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminCampusesNewRouteImport } from './routes/admin.campuses.new'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeSuperAdminRoute = ScopeSuperAdminRouteImport.update({
  id: '/scope-super-admin',
  path: '/scope-super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeAdminRoute = ScopeAdminRouteImport.update({
  id: '/scope-admin',
  path: '/scope-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionAdminRoute = InstitutionAdminRouteImport.update({
  id: '/institution-admin',
  path: '/institution-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationLabRoute = InnovationLabRouteImport.update({
  id: '/innovation-lab',
  path: '/innovation-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLeaderRoute = CampusLeaderRouteImport.update({
  id: '/campus-leader',
  path: '/campus-leader',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokenLinkRoute = BrokenLinkRouteImport.update({
  id: '/broken-link',
  path: '/broken-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRoute = AmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeSuperAdminRbacAuditRoute =
  ScopeSuperAdminRbacAuditRouteImport.update({
    id: '/rbac-audit',
    path: '/rbac-audit',
    getParentRoute: () => ScopeSuperAdminRoute,
  } as any)
const ScopeAdminVisitsRoute = ScopeAdminVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => ScopeAdminRoute,
} as any)
const ScopeAdminReportsRoute = ScopeAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ScopeAdminRoute,
} as any)
const ScopeAdminMouPipelineRoute = ScopeAdminMouPipelineRouteImport.update({
  id: '/mou-pipeline',
  path: '/mou-pipeline',
  getParentRoute: () => ScopeAdminRoute,
} as any)
const ScopeAdminInstitutionsRoute = ScopeAdminInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => ScopeAdminRoute,
} as any)
const ScopeAdminDashboardRoute = ScopeAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ScopeAdminRoute,
} as any)
const InstitutionReportsRoute = InstitutionReportsRouteImport.update({
  id: '/institution/reports',
  path: '/institution/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionAdminReportsRoute = InstitutionAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => InstitutionAdminRoute,
} as any)
const InstitutionAdminMembersRoute = InstitutionAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => InstitutionAdminRoute,
} as any)
const InstitutionAdminCommunicationsRoute =
  InstitutionAdminCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => InstitutionAdminRoute,
  } as any)
const InstitutionAdminAnalyticsRoute =
  InstitutionAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => InstitutionAdminRoute,
  } as any)
const FormsFormSlugRoute = FormsFormSlugRouteImport.update({
  id: '/forms/$formSlug',
  path: '/forms/$formSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBuildDiagnosticsRoute = DevBuildDiagnosticsRouteImport.update({
  id: '/dev/build-diagnostics',
  path: '/dev/build-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampusesNewRoute = AdminCampusesNewRouteImport.update({
  id: '/campuses/new',
  path: '/campuses/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ambassador': typeof AmbassadorRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/broken-link': typeof BrokenLinkRoute
  '/campus': typeof CampusRoute
  '/campus-leader': typeof CampusLeaderRoute
  '/challenges': typeof ChallengesRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/faqs': typeof FaqsRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/institution-admin': typeof InstitutionAdminRouteWithChildren
  '/leaderboards': typeof LeaderboardsRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/ops': typeof OpsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/refer': typeof ReferRoute
  '/scope-admin': typeof ScopeAdminRouteWithChildren
  '/scope-super-admin': typeof ScopeSuperAdminRouteWithChildren
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/updates': typeof UpdatesRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/config': typeof AdminConfigRoute
  '/dev/build-diagnostics': typeof DevBuildDiagnosticsRoute
  '/forms/$formSlug': typeof FormsFormSlugRoute
  '/institution-admin/analytics': typeof InstitutionAdminAnalyticsRoute
  '/institution-admin/communications': typeof InstitutionAdminCommunicationsRoute
  '/institution-admin/members': typeof InstitutionAdminMembersRoute
  '/institution-admin/reports': typeof InstitutionAdminReportsRoute
  '/institution/reports': typeof InstitutionReportsRoute
  '/scope-admin/dashboard': typeof ScopeAdminDashboardRoute
  '/scope-admin/institutions': typeof ScopeAdminInstitutionsRoute
  '/scope-admin/mou-pipeline': typeof ScopeAdminMouPipelineRoute
  '/scope-admin/reports': typeof ScopeAdminReportsRoute
  '/scope-admin/visits': typeof ScopeAdminVisitsRoute
  '/scope-super-admin/rbac-audit': typeof ScopeSuperAdminRbacAuditRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/campuses/new': typeof AdminCampusesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ambassador': typeof AmbassadorRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/broken-link': typeof BrokenLinkRoute
  '/campus': typeof CampusRoute
  '/campus-leader': typeof CampusLeaderRoute
  '/challenges': typeof ChallengesRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/faqs': typeof FaqsRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/institution-admin': typeof InstitutionAdminRouteWithChildren
  '/leaderboards': typeof LeaderboardsRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/ops': typeof OpsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/refer': typeof ReferRoute
  '/scope-admin': typeof ScopeAdminRouteWithChildren
  '/scope-super-admin': typeof ScopeSuperAdminRouteWithChildren
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/updates': typeof UpdatesRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/config': typeof AdminConfigRoute
  '/dev/build-diagnostics': typeof DevBuildDiagnosticsRoute
  '/forms/$formSlug': typeof FormsFormSlugRoute
  '/institution-admin/analytics': typeof InstitutionAdminAnalyticsRoute
  '/institution-admin/communications': typeof InstitutionAdminCommunicationsRoute
  '/institution-admin/members': typeof InstitutionAdminMembersRoute
  '/institution-admin/reports': typeof InstitutionAdminReportsRoute
  '/institution/reports': typeof InstitutionReportsRoute
  '/scope-admin/dashboard': typeof ScopeAdminDashboardRoute
  '/scope-admin/institutions': typeof ScopeAdminInstitutionsRoute
  '/scope-admin/mou-pipeline': typeof ScopeAdminMouPipelineRoute
  '/scope-admin/reports': typeof ScopeAdminReportsRoute
  '/scope-admin/visits': typeof ScopeAdminVisitsRoute
  '/scope-super-admin/rbac-audit': typeof ScopeSuperAdminRbacAuditRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/campuses/new': typeof AdminCampusesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ambassador': typeof AmbassadorRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/broken-link': typeof BrokenLinkRoute
  '/campus': typeof CampusRoute
  '/campus-leader': typeof CampusLeaderRoute
  '/challenges': typeof ChallengesRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/faqs': typeof FaqsRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/institution-admin': typeof InstitutionAdminRouteWithChildren
  '/leaderboards': typeof LeaderboardsRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/ops': typeof OpsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/refer': typeof ReferRoute
  '/scope-admin': typeof ScopeAdminRouteWithChildren
  '/scope-super-admin': typeof ScopeSuperAdminRouteWithChildren
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/updates': typeof UpdatesRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/config': typeof AdminConfigRoute
  '/dev/build-diagnostics': typeof DevBuildDiagnosticsRoute
  '/forms/$formSlug': typeof FormsFormSlugRoute
  '/institution-admin/analytics': typeof InstitutionAdminAnalyticsRoute
  '/institution-admin/communications': typeof InstitutionAdminCommunicationsRoute
  '/institution-admin/members': typeof InstitutionAdminMembersRoute
  '/institution-admin/reports': typeof InstitutionAdminReportsRoute
  '/institution/reports': typeof InstitutionReportsRoute
  '/scope-admin/dashboard': typeof ScopeAdminDashboardRoute
  '/scope-admin/institutions': typeof ScopeAdminInstitutionsRoute
  '/scope-admin/mou-pipeline': typeof ScopeAdminMouPipelineRoute
  '/scope-admin/reports': typeof ScopeAdminReportsRoute
  '/scope-admin/visits': typeof ScopeAdminVisitsRoute
  '/scope-super-admin/rbac-audit': typeof ScopeSuperAdminRbacAuditRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/campuses/new': typeof AdminCampusesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ambassador'
    | '/announcements'
    | '/auth'
    | '/broken-link'
    | '/campus'
    | '/campus-leader'
    | '/challenges'
    | '/community-guidelines'
    | '/contact'
    | '/cookie-policy'
    | '/dashboard'
    | '/events'
    | '/faculty'
    | '/faqs'
    | '/feed'
    | '/feedback'
    | '/innovation-lab'
    | '/institution-admin'
    | '/leaderboards'
    | '/notifications'
    | '/opportunities'
    | '/ops'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/projects'
    | '/refer'
    | '/scope-admin'
    | '/scope-super-admin'
    | '/settings'
    | '/support'
    | '/terms'
    | '/unauthorized'
    | '/updates'
    | '/waitlist'
    | '/admin/config'
    | '/dev/build-diagnostics'
    | '/forms/$formSlug'
    | '/institution-admin/analytics'
    | '/institution-admin/communications'
    | '/institution-admin/members'
    | '/institution-admin/reports'
    | '/institution/reports'
    | '/scope-admin/dashboard'
    | '/scope-admin/institutions'
    | '/scope-admin/mou-pipeline'
    | '/scope-admin/reports'
    | '/scope-admin/visits'
    | '/scope-super-admin/rbac-audit'
    | '/u/$handle'
    | '/admin/campuses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ambassador'
    | '/announcements'
    | '/auth'
    | '/broken-link'
    | '/campus'
    | '/campus-leader'
    | '/challenges'
    | '/community-guidelines'
    | '/contact'
    | '/cookie-policy'
    | '/dashboard'
    | '/events'
    | '/faculty'
    | '/faqs'
    | '/feed'
    | '/feedback'
    | '/innovation-lab'
    | '/institution-admin'
    | '/leaderboards'
    | '/notifications'
    | '/opportunities'
    | '/ops'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/projects'
    | '/refer'
    | '/scope-admin'
    | '/scope-super-admin'
    | '/settings'
    | '/support'
    | '/terms'
    | '/unauthorized'
    | '/updates'
    | '/waitlist'
    | '/admin/config'
    | '/dev/build-diagnostics'
    | '/forms/$formSlug'
    | '/institution-admin/analytics'
    | '/institution-admin/communications'
    | '/institution-admin/members'
    | '/institution-admin/reports'
    | '/institution/reports'
    | '/scope-admin/dashboard'
    | '/scope-admin/institutions'
    | '/scope-admin/mou-pipeline'
    | '/scope-admin/reports'
    | '/scope-admin/visits'
    | '/scope-super-admin/rbac-audit'
    | '/u/$handle'
    | '/admin/campuses/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ambassador'
    | '/announcements'
    | '/auth'
    | '/broken-link'
    | '/campus'
    | '/campus-leader'
    | '/challenges'
    | '/community-guidelines'
    | '/contact'
    | '/cookie-policy'
    | '/dashboard'
    | '/events'
    | '/faculty'
    | '/faqs'
    | '/feed'
    | '/feedback'
    | '/innovation-lab'
    | '/institution-admin'
    | '/leaderboards'
    | '/notifications'
    | '/opportunities'
    | '/ops'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/projects'
    | '/refer'
    | '/scope-admin'
    | '/scope-super-admin'
    | '/settings'
    | '/support'
    | '/terms'
    | '/unauthorized'
    | '/updates'
    | '/waitlist'
    | '/admin/config'
    | '/dev/build-diagnostics'
    | '/forms/$formSlug'
    | '/institution-admin/analytics'
    | '/institution-admin/communications'
    | '/institution-admin/members'
    | '/institution-admin/reports'
    | '/institution/reports'
    | '/scope-admin/dashboard'
    | '/scope-admin/institutions'
    | '/scope-admin/mou-pipeline'
    | '/scope-admin/reports'
    | '/scope-admin/visits'
    | '/scope-super-admin/rbac-audit'
    | '/u/$handle'
    | '/admin/campuses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AmbassadorRoute: typeof AmbassadorRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  BrokenLinkRoute: typeof BrokenLinkRoute
  CampusRoute: typeof CampusRoute
  CampusLeaderRoute: typeof CampusLeaderRoute
  ChallengesRoute: typeof ChallengesRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  FacultyRoute: typeof FacultyRoute
  FaqsRoute: typeof FaqsRoute
  FeedRoute: typeof FeedRoute
  FeedbackRoute: typeof FeedbackRoute
  InnovationLabRoute: typeof InnovationLabRoute
  InstitutionAdminRoute: typeof InstitutionAdminRouteWithChildren
  LeaderboardsRoute: typeof LeaderboardsRoute
  NotificationsRoute: typeof NotificationsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OpsRoute: typeof OpsRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ReferRoute: typeof ReferRoute
  ScopeAdminRoute: typeof ScopeAdminRouteWithChildren
  ScopeSuperAdminRoute: typeof ScopeSuperAdminRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UpdatesRoute: typeof UpdatesRoute
  WaitlistRoute: typeof WaitlistRoute
  DevBuildDiagnosticsRoute: typeof DevBuildDiagnosticsRoute
  FormsFormSlugRoute: typeof FormsFormSlugRoute
  InstitutionReportsRoute: typeof InstitutionReportsRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope-super-admin': {
      id: '/scope-super-admin'
      path: '/scope-super-admin'
      fullPath: '/scope-super-admin'
      preLoaderRoute: typeof ScopeSuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope-admin': {
      id: '/scope-admin'
      path: '/scope-admin'
      fullPath: '/scope-admin'
      preLoaderRoute: typeof ScopeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution-admin': {
      id: '/institution-admin'
      path: '/institution-admin'
      fullPath: '/institution-admin'
      preLoaderRoute: typeof InstitutionAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-lab': {
      id: '/innovation-lab'
      path: '/innovation-lab'
      fullPath: '/innovation-lab'
      preLoaderRoute: typeof InnovationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-leader': {
      id: '/campus-leader'
      path: '/campus-leader'
      fullPath: '/campus-leader'
      preLoaderRoute: typeof CampusLeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broken-link': {
      id: '/broken-link'
      path: '/broken-link'
      fullPath: '/broken-link'
      preLoaderRoute: typeof BrokenLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador': {
      id: '/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope-super-admin/rbac-audit': {
      id: '/scope-super-admin/rbac-audit'
      path: '/rbac-audit'
      fullPath: '/scope-super-admin/rbac-audit'
      preLoaderRoute: typeof ScopeSuperAdminRbacAuditRouteImport
      parentRoute: typeof ScopeSuperAdminRoute
    }
    '/scope-admin/visits': {
      id: '/scope-admin/visits'
      path: '/visits'
      fullPath: '/scope-admin/visits'
      preLoaderRoute: typeof ScopeAdminVisitsRouteImport
      parentRoute: typeof ScopeAdminRoute
    }
    '/scope-admin/reports': {
      id: '/scope-admin/reports'
      path: '/reports'
      fullPath: '/scope-admin/reports'
      preLoaderRoute: typeof ScopeAdminReportsRouteImport
      parentRoute: typeof ScopeAdminRoute
    }
    '/scope-admin/mou-pipeline': {
      id: '/scope-admin/mou-pipeline'
      path: '/mou-pipeline'
      fullPath: '/scope-admin/mou-pipeline'
      preLoaderRoute: typeof ScopeAdminMouPipelineRouteImport
      parentRoute: typeof ScopeAdminRoute
    }
    '/scope-admin/institutions': {
      id: '/scope-admin/institutions'
      path: '/institutions'
      fullPath: '/scope-admin/institutions'
      preLoaderRoute: typeof ScopeAdminInstitutionsRouteImport
      parentRoute: typeof ScopeAdminRoute
    }
    '/scope-admin/dashboard': {
      id: '/scope-admin/dashboard'
      path: '/dashboard'
      fullPath: '/scope-admin/dashboard'
      preLoaderRoute: typeof ScopeAdminDashboardRouteImport
      parentRoute: typeof ScopeAdminRoute
    }
    '/institution/reports': {
      id: '/institution/reports'
      path: '/institution/reports'
      fullPath: '/institution/reports'
      preLoaderRoute: typeof InstitutionReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution-admin/reports': {
      id: '/institution-admin/reports'
      path: '/reports'
      fullPath: '/institution-admin/reports'
      preLoaderRoute: typeof InstitutionAdminReportsRouteImport
      parentRoute: typeof InstitutionAdminRoute
    }
    '/institution-admin/members': {
      id: '/institution-admin/members'
      path: '/members'
      fullPath: '/institution-admin/members'
      preLoaderRoute: typeof InstitutionAdminMembersRouteImport
      parentRoute: typeof InstitutionAdminRoute
    }
    '/institution-admin/communications': {
      id: '/institution-admin/communications'
      path: '/communications'
      fullPath: '/institution-admin/communications'
      preLoaderRoute: typeof InstitutionAdminCommunicationsRouteImport
      parentRoute: typeof InstitutionAdminRoute
    }
    '/institution-admin/analytics': {
      id: '/institution-admin/analytics'
      path: '/analytics'
      fullPath: '/institution-admin/analytics'
      preLoaderRoute: typeof InstitutionAdminAnalyticsRouteImport
      parentRoute: typeof InstitutionAdminRoute
    }
    '/forms/$formSlug': {
      id: '/forms/$formSlug'
      path: '/forms/$formSlug'
      fullPath: '/forms/$formSlug'
      preLoaderRoute: typeof FormsFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/build-diagnostics': {
      id: '/dev/build-diagnostics'
      path: '/dev/build-diagnostics'
      fullPath: '/dev/build-diagnostics'
      preLoaderRoute: typeof DevBuildDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campuses/new': {
      id: '/admin/campuses/new'
      path: '/campuses/new'
      fullPath: '/admin/campuses/new'
      preLoaderRoute: typeof AdminCampusesNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCampusesNewRoute: typeof AdminCampusesNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfigRoute: AdminConfigRoute,
  AdminCampusesNewRoute: AdminCampusesNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InstitutionAdminRouteChildren {
  InstitutionAdminAnalyticsRoute: typeof InstitutionAdminAnalyticsRoute
  InstitutionAdminCommunicationsRoute: typeof InstitutionAdminCommunicationsRoute
  InstitutionAdminMembersRoute: typeof InstitutionAdminMembersRoute
  InstitutionAdminReportsRoute: typeof InstitutionAdminReportsRoute
}

const InstitutionAdminRouteChildren: InstitutionAdminRouteChildren = {
  InstitutionAdminAnalyticsRoute: InstitutionAdminAnalyticsRoute,
  InstitutionAdminCommunicationsRoute: InstitutionAdminCommunicationsRoute,
  InstitutionAdminMembersRoute: InstitutionAdminMembersRoute,
  InstitutionAdminReportsRoute: InstitutionAdminReportsRoute,
}

const InstitutionAdminRouteWithChildren =
  InstitutionAdminRoute._addFileChildren(InstitutionAdminRouteChildren)

interface ScopeAdminRouteChildren {
  ScopeAdminDashboardRoute: typeof ScopeAdminDashboardRoute
  ScopeAdminInstitutionsRoute: typeof ScopeAdminInstitutionsRoute
  ScopeAdminMouPipelineRoute: typeof ScopeAdminMouPipelineRoute
  ScopeAdminReportsRoute: typeof ScopeAdminReportsRoute
  ScopeAdminVisitsRoute: typeof ScopeAdminVisitsRoute
}

const ScopeAdminRouteChildren: ScopeAdminRouteChildren = {
  ScopeAdminDashboardRoute: ScopeAdminDashboardRoute,
  ScopeAdminInstitutionsRoute: ScopeAdminInstitutionsRoute,
  ScopeAdminMouPipelineRoute: ScopeAdminMouPipelineRoute,
  ScopeAdminReportsRoute: ScopeAdminReportsRoute,
  ScopeAdminVisitsRoute: ScopeAdminVisitsRoute,
}

const ScopeAdminRouteWithChildren = ScopeAdminRoute._addFileChildren(
  ScopeAdminRouteChildren,
)

interface ScopeSuperAdminRouteChildren {
  ScopeSuperAdminRbacAuditRoute: typeof ScopeSuperAdminRbacAuditRoute
}

const ScopeSuperAdminRouteChildren: ScopeSuperAdminRouteChildren = {
  ScopeSuperAdminRbacAuditRoute: ScopeSuperAdminRbacAuditRoute,
}

const ScopeSuperAdminRouteWithChildren = ScopeSuperAdminRoute._addFileChildren(
  ScopeSuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AmbassadorRoute: AmbassadorRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  BrokenLinkRoute: BrokenLinkRoute,
  CampusRoute: CampusRoute,
  CampusLeaderRoute: CampusLeaderRoute,
  ChallengesRoute: ChallengesRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  FacultyRoute: FacultyRoute,
  FaqsRoute: FaqsRoute,
  FeedRoute: FeedRoute,
  FeedbackRoute: FeedbackRoute,
  InnovationLabRoute: InnovationLabRoute,
  InstitutionAdminRoute: InstitutionAdminRouteWithChildren,
  LeaderboardsRoute: LeaderboardsRoute,
  NotificationsRoute: NotificationsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OpsRoute: OpsRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ReferRoute: ReferRoute,
  ScopeAdminRoute: ScopeAdminRouteWithChildren,
  ScopeSuperAdminRoute: ScopeSuperAdminRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UpdatesRoute: UpdatesRoute,
  WaitlistRoute: WaitlistRoute,
  DevBuildDiagnosticsRoute: DevBuildDiagnosticsRoute,
  FormsFormSlugRoute: FormsFormSlugRoute,
  InstitutionReportsRoute: InstitutionReportsRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
