// Mock data for Scope Connect — seeded ecosystem.
// Hand-tuned for "launch full, not empty": realistic Indian campus context,
// rich variety, and enough volume that every page feels in motion.

export const campusPartners = [
  { name: "IIT Bombay", city: "Mumbai", members: 842 },
  { name: "BITS Pilani", city: "Pilani", members: 654 },
  { name: "VIT Vellore", city: "Vellore", members: 591 },
  { name: "NIT Trichy", city: "Trichy", members: 478 },
  { name: "IIIT Hyderabad", city: "Hyderabad", members: 433 },
  { name: "Manipal University", city: "Manipal", members: 402 },
  { name: "DTU Delhi", city: "New Delhi", members: 388 },
  { name: "SRM University", city: "Chennai", members: 365 },
  { name: "Jadavpur University", city: "Kolkata", members: 342 },
  { name: "St. Xavier's", city: "Kolkata", members: 298 },
  { name: "Heritage Institute", city: "Kolkata", members: 264 },
  { name: "Amity Kolkata", city: "Kolkata", members: 231 },
];

export const liveMetrics = [
  { label: "Campus Partners", value: "142+", change: "+18 this month" },
  { label: "Active Members", value: "12,480", change: "+1.2k this week" },
  { label: "Projects Shipped", value: "3,210", change: "+86 today" },
  { label: "Cities", value: "68", change: "across India" },
];

export const topChapters = [
  { name: "AI Builders Mumbai", campus: "IIT Bombay", members: 142, rank: 1, growth: "+24%" },
  { name: "Startup Sprint BITS", campus: "BITS Pilani", members: 128, rank: 2, growth: "+19%" },
  { name: "Design Lab Vellore", campus: "VIT Vellore", members: 116, rank: 3, growth: "+15%" },
  { name: "RoboTrichy", campus: "NIT Trichy", members: 98, rank: 4, growth: "+12%" },
  { name: "ContentCo Hyderabad", campus: "IIIT Hyderabad", members: 87, rank: 5, growth: "+11%" },
  { name: "Kolkata Builders Collective", campus: "Jadavpur University", members: 79, rank: 6, growth: "+22%" },
  { name: "Founders Forum Manipal", campus: "Manipal University", members: 71, rank: 7, growth: "+9%" },
  { name: "Delhi Design Sprint", campus: "DTU Delhi", members: 64, rank: 8, growth: "+8%" },
];

// 60+ realistic Indian campus builders for leaderboards, feed, collaborator lists.
export const topBuilders = [
  { name: "Aarav Mehta", campus: "IIT Bombay", level: "Innovator", points: 4820, badge: "🏆", role: "Founder" },
  { name: "Diya Sharma", campus: "BITS Pilani", level: "Leader", points: 4560, badge: "⚡", role: "Founder" },
  { name: "Kabir Singh", campus: "VIT Vellore", level: "Builder", points: 4210, badge: "🚀", role: "Developer" },
  { name: "Ananya Iyer", campus: "IIIT Hyderabad", level: "Innovator", points: 3980, badge: "💡", role: "Designer" },
  { name: "Rohan Das", campus: "NIT Trichy", level: "Builder", points: 3740, badge: "🔥", role: "Developer" },
  { name: "Meera Nair", campus: "Manipal University", level: "Ambassador", points: 3620, badge: "🌟", role: "Community Lead" },
  { name: "Ishaan Kapoor", campus: "DTU Delhi", level: "Innovator", points: 3540, badge: "🛠", role: "Developer" },
  { name: "Saanvi Rao", campus: "SRM University", level: "Builder", points: 3410, badge: "✨", role: "Designer" },
  { name: "Arjun Verma", campus: "Jadavpur University", level: "Leader", points: 3360, badge: "🎯", role: "Researcher" },
  { name: "Tanvi Bose", campus: "St. Xavier's", level: "Builder", points: 3280, badge: "📚", role: "Researcher" },
  { name: "Vivaan Joshi", campus: "Heritage Institute", level: "Innovator", points: 3210, badge: "🧪", role: "Developer" },
  { name: "Riya Chatterjee", campus: "Amity Kolkata", level: "Builder", points: 3140, badge: "🎨", role: "Designer" },
  { name: "Aditya Pillai", campus: "IIT Bombay", level: "Innovator", points: 3080, badge: "📈", role: "Marketer" },
  { name: "Pooja Reddy", campus: "IIIT Hyderabad", level: "Builder", points: 2990, badge: "🌐", role: "Marketer" },
  { name: "Karthik Subramanian", campus: "VIT Vellore", level: "Builder", points: 2940, badge: "⚙️", role: "Developer" },
  { name: "Neha Bansal", campus: "DTU Delhi", level: "Builder", points: 2880, badge: "📝", role: "Marketer" },
  { name: "Rahul Khanna", campus: "BITS Pilani", level: "Builder", points: 2830, badge: "🧠", role: "Researcher" },
  { name: "Sneha Patil", campus: "Manipal University", level: "Builder", points: 2770, badge: "💬", role: "Community Lead" },
  { name: "Vikram Sethi", campus: "NIT Trichy", level: "Builder", points: 2710, badge: "🤖", role: "Developer" },
  { name: "Priya Menon", campus: "SRM University", level: "Builder", points: 2660, badge: "🎤", role: "Community Lead" },
  { name: "Aryan Gupta", campus: "Jadavpur University", level: "Builder", points: 2610, badge: "💼", role: "Founder" },
  { name: "Kriti Saxena", campus: "St. Xavier's", level: "Builder", points: 2570, badge: "📷", role: "Designer" },
  { name: "Devansh Roy", campus: "Heritage Institute", level: "Builder", points: 2520, badge: "🏗", role: "Developer" },
  { name: "Aisha Khan", campus: "Amity Kolkata", level: "Builder", points: 2480, badge: "🌱", role: "Founder" },
  { name: "Rudra Bhattacharya", campus: "Jadavpur University", level: "Builder", points: 2430, badge: "📊", role: "Researcher" },
  { name: "Ira Ghosh", campus: "St. Xavier's", level: "Explorer", points: 2390, badge: "📰", role: "Marketer" },
  { name: "Yash Agarwal", campus: "IIT Bombay", level: "Builder", points: 2340, badge: "🧮", role: "Researcher" },
  { name: "Nandini Shah", campus: "BITS Pilani", level: "Builder", points: 2280, badge: "🎬", role: "Designer" },
  { name: "Harsh Vardhan", campus: "VIT Vellore", level: "Builder", points: 2220, badge: "🛡", role: "Developer" },
  { name: "Tara Krishnan", campus: "IIIT Hyderabad", level: "Builder", points: 2170, badge: "🔬", role: "Researcher" },
  { name: "Mihir Jain", campus: "NIT Trichy", level: "Builder", points: 2120, badge: "🪐", role: "Developer" },
  { name: "Shreya Kulkarni", campus: "Manipal University", level: "Builder", points: 2080, badge: "🎯", role: "Marketer" },
  { name: "Aakash Pandey", campus: "DTU Delhi", level: "Builder", points: 2030, badge: "🧰", role: "Developer" },
  { name: "Anvi Trivedi", campus: "SRM University", level: "Explorer", points: 1980, badge: "🌸", role: "Designer" },
  { name: "Rajat Mukherjee", campus: "Jadavpur University", level: "Builder", points: 1940, badge: "🪄", role: "Founder" },
  { name: "Bhavya Seth", campus: "St. Xavier's", level: "Explorer", points: 1890, badge: "📖", role: "Researcher" },
  { name: "Shivansh Mishra", campus: "Heritage Institute", level: "Builder", points: 1840, badge: "🧱", role: "Developer" },
  { name: "Mahi Banerjee", campus: "Amity Kolkata", level: "Explorer", points: 1790, badge: "🪶", role: "Designer" },
  { name: "Dev Patel", campus: "IIT Bombay", level: "Builder", points: 1740, badge: "🔋", role: "Developer" },
  { name: "Naina Choudhary", campus: "BITS Pilani", level: "Explorer", points: 1690, badge: "💌", role: "Marketer" },
  { name: "Parth Joshi", campus: "VIT Vellore", level: "Explorer", points: 1640, badge: "🎮", role: "Developer" },
  { name: "Avni Sharma", campus: "IIIT Hyderabad", level: "Explorer", points: 1590, badge: "🌼", role: "Designer" },
  { name: "Krish Malhotra", campus: "NIT Trichy", level: "Explorer", points: 1540, badge: "🛰", role: "Researcher" },
  { name: "Aanya Chopra", campus: "Manipal University", level: "Explorer", points: 1490, badge: "🎺", role: "Community Lead" },
  { name: "Reyansh Goel", campus: "DTU Delhi", level: "Explorer", points: 1440, badge: "🧗", role: "Founder" },
  { name: "Myra Kapoor", campus: "SRM University", level: "Explorer", points: 1390, badge: "🪩", role: "Marketer" },
  { name: "Veer Sengupta", campus: "Jadavpur University", level: "Explorer", points: 1340, badge: "🧭", role: "Developer" },
  { name: "Zoya Dutta", campus: "St. Xavier's", level: "Explorer", points: 1290, badge: "📿", role: "Researcher" },
  { name: "Yuvraj Saha", campus: "Heritage Institute", level: "Explorer", points: 1240, badge: "🚲", role: "Marketer" },
  { name: "Inaya Mitra", campus: "Amity Kolkata", level: "Explorer", points: 1190, badge: "🎈", role: "Community Lead" },
  { name: "Atharv Bhasin", campus: "IIT Bombay", level: "Explorer", points: 1140, badge: "🎓", role: "Developer" },
  { name: "Siya Aggarwal", campus: "BITS Pilani", level: "Explorer", points: 1090, badge: "🌷", role: "Designer" },
  { name: "Om Prakash", campus: "VIT Vellore", level: "Explorer", points: 1040, badge: "🪔", role: "Founder" },
  { name: "Kavya Ramesh", campus: "IIIT Hyderabad", level: "Explorer", points: 990, badge: "🎻", role: "Community Lead" },
  { name: "Hridaan Sinha", campus: "NIT Trichy", level: "Explorer", points: 940, badge: "🧬", role: "Researcher" },
  { name: "Sara Pillai", campus: "Manipal University", level: "Explorer", points: 890, badge: "🏵", role: "Designer" },
  { name: "Aryaman Tiwari", campus: "DTU Delhi", level: "Explorer", points: 840, badge: "🛹", role: "Developer" },
  { name: "Noor Fatima", campus: "SRM University", level: "Explorer", points: 790, badge: "🌙", role: "Marketer" },
  { name: "Vihaan Sen", campus: "Jadavpur University", level: "Explorer", points: 740, badge: "🦉", role: "Researcher" },
  { name: "Pari Lahiri", campus: "St. Xavier's", level: "Explorer", points: 690, badge: "🌻", role: "Community Lead" },
  { name: "Ekansh Roy", campus: "Heritage Institute", level: "Explorer", points: 640, badge: "🏃", role: "Founder" },
];

export const featuredProjects = [
  {
    title: "MediMatch AI",
    description: "AI-powered symptom triage matching patients to specialists in <30s.",
    category: "AI",
    team: "AI Builders Mumbai",
    votes: 482,
    cover: "🩺",
  },
  {
    title: "CampusDAO",
    description: "Decentralized treasury & voting platform for student societies.",
    category: "Web",
    team: "Startup Sprint BITS",
    votes: 391,
    cover: "🏛️",
  },
  {
    title: "InkFlow",
    description: "Notion-grade design tool built for student creators.",
    category: "Design",
    team: "Design Lab Vellore",
    votes: 356,
    cover: "🎨",
  },
  {
    title: "Sprintly",
    description: "Hackathon-in-a-box: form teams, ship MVPs, present in 48h.",
    category: "Startup",
    team: "ContentCo Hyderabad",
    votes: 312,
    cover: "⚡",
  },
  {
    title: "SwarmBots",
    description: "Open-source swarm robotics framework for under-graduate research.",
    category: "Robotics",
    team: "RoboTrichy",
    votes: 287,
    cover: "🤖",
  },
  {
    title: "PitchCanvas",
    description: "AI co-pilot that turns 1-line ideas into investor-ready decks.",
    category: "AI",
    team: "Builders Delhi",
    votes: 264,
    cover: "📊",
  },
  {
    title: "ChaiChat",
    description: "Async-first community OS for campus chapters and study circles.",
    category: "Web",
    team: "Kolkata Builders Collective",
    votes: 241,
    cover: "💬",
  },
  {
    title: "GreenLedger",
    description: "Track and reduce your hostel's carbon footprint with weekly nudges.",
    category: "Climate",
    team: "Founders Forum Manipal",
    votes: 218,
    cover: "🌿",
  },
];

export const upcomingEvents = [
  {
    title: "Scope Hack '26",
    type: "Hackathon",
    date: "May 15–17",
    venue: "Pan-India · Hybrid",
    seats: 2400,
    color: "brand",
  },
  {
    title: "AI Founders Sprint",
    type: "Sprint",
    date: "Apr 28",
    venue: "Bengaluru",
    seats: 180,
    color: "cyan",
  },
  {
    title: "Pitch Battle: Series 04",
    type: "Pitch Battle",
    date: "May 04",
    venue: "Mumbai · IIT Bombay",
    seats: 320,
    color: "primary",
  },
  {
    title: "Design Systems Workshop",
    type: "Workshop",
    date: "Apr 30",
    venue: "Online",
    seats: 500,
    color: "cyan",
  },
  {
    title: "Design Portfolio Roast Night",
    type: "Portfolio Review",
    date: "May 02",
    venue: "Online",
    seats: 220,
    color: "cyan",
  },
  {
    title: "Build in Public Workshop",
    type: "Workshop",
    date: "May 09",
    venue: "Hyderabad · IIIT",
    seats: 160,
    color: "primary",
  },
  {
    title: "Founder AMA — Layerly (YC W25)",
    type: "AMA Session",
    date: "May 11",
    venue: "Online",
    seats: 600,
    color: "brand",
  },
  {
    title: "Kolkata Campus Sprint",
    type: "Campus Sprint",
    date: "May 18",
    venue: "Jadavpur University",
    seats: 240,
    color: "cyan",
  },
  {
    title: "Research Showcase: Mental Health Report",
    type: "Showcase",
    date: "May 22",
    venue: "Online",
    seats: 800,
    color: "primary",
  },
  {
    title: "Founder Meetup — South Zone",
    type: "Founder Meetup",
    date: "May 25",
    venue: "Bengaluru",
    seats: 120,
    color: "brand",
  },
];

export const testimonials = [
  {
    quote: "Scope Connect gave me a national stage as a sophomore. I went from coding alone to leading a 40-person chapter in 6 months.",
    name: "Priya R.",
    role: "Chapter President · VIT Vellore",
  },
  {
    quote: "We hired 3 interns from Scope Connect's builder marketplace. The talent density is unreal.",
    name: "Karan G.",
    role: "Founder · Layerly (YC W25)",
  },
  {
    quote: "It's the first platform that actually feels built for Gen Z campus builders — not LinkedIn cosplay.",
    name: "Ishita V.",
    role: "Innovator · IIIT Hyderabad",
  },
  {
    quote: "Scope helped me build real proof of work before placements. My portfolio finally tells a story.",
    name: "Aryan G.",
    role: "Builder · Jadavpur University",
  },
  {
    quote: "Our chapter became 3× more active after joining Scope Connect. The challenges give us a reason to ship every week.",
    name: "Tanvi B.",
    role: "Chapter Lead · St. Xavier's",
  },
  {
    quote: "I found my co-founder across campuses on Scope. We're now building a startup together full-time.",
    name: "Devansh R.",
    role: "Founder · Heritage Institute",
  },
  {
    quote: "The Scope Mental Health Report I co-authored is being read across 100+ campuses. That's surreal as an undergrad.",
    name: "Bhavya S.",
    role: "Researcher · St. Xavier's",
  },
  {
    quote: "Scope's design challenge was the most professional brief I've worked on as a student. Real users, real shipping deadline.",
    name: "Saanvi R.",
    role: "Designer · SRM University",
  },
];

export const feedPosts = [
  { id: "1", author: "Aarav Mehta", campus: "IIT Bombay", time: "12m", type: "Project Launch",
    content: "Just shipped v1 of MediMatch AI 🩺 — triages symptoms to the right specialist in under 30 seconds. Built with my team at AI Builders Mumbai. Would love feedback!",
    likes: 142, comments: 28, celebrates: 56 },
  { id: "2", author: "Diya Sharma", campus: "BITS Pilani", time: "1h", type: "Achievement",
    content: "Hit 4,500 Scope Points 🚀 Officially a Leader-tier builder. Thank you to everyone in Startup Sprint BITS for the late-night brainstorms.",
    likes: 318, comments: 64, celebrates: 201 },
  { id: "3", author: "Scope Connect", campus: "National HQ", time: "3h", type: "Campus Growth Milestone",
    content: "🎉 We just crossed 12,000 active members across 142 campuses. Onwards to 50,000 by end of year. Tag your campus chapter below 👇",
    likes: 892, comments: 184, celebrates: 612 },
  { id: "4", author: "Karan G.", campus: "Recruiter · Layerly", time: "5h", type: "Hiring Opportunity",
    content: "We're hiring 2 frontend interns (React + Tailwind) for summer '26. Open to all campuses. DM your portfolio + Scope profile.",
    likes: 246, comments: 92, celebrates: 38 },
  { id: "5", author: "Ananya Iyer", campus: "IIIT Hyderabad", time: "8h", type: "Event Update",
    content: "Our pitch battle finalists are LIVE on Scope Events 🔥 Voting closes at midnight. Show your campus some love.",
    likes: 184, comments: 41, celebrates: 73 },
  { id: "6", author: "Scope Connect", campus: "National HQ", time: "10h", type: "Challenge Launched",
    content: "🚀 New AI challenge live: Build an AI Study Planner for Students. 8 seats, 6-week sprint, ₹25k stipend + Scope Spotlight.",
    likes: 421, comments: 87, celebrates: 213 },
  { id: "7", author: "Kolkata Builders Collective", campus: "Jadavpur University", time: "11h", type: "Campus Climbed Leaderboard",
    content: "Kolkata builders moved to #2 nationally this week. 79 active members, +22% growth. Calcutta is shipping 🔥",
    likes: 512, comments: 96, celebrates: 304 },
  { id: "8", author: "Riya Chatterjee", campus: "Amity Kolkata", time: "13h", type: "Portfolio Spotlight",
    content: "Added my Scope Connect mobile UI pack to my portfolio. 12 screens, fully prototyped. Looking for design collabs ✨",
    likes: 168, comments: 34, celebrates: 71 },
  { id: "9", author: "Vivaan Joshi", campus: "Heritage Institute", time: "15h", type: "Builder Milestone",
    content: "Designer from EIILM completed Level 5. Three years of grind, finally feels real 💪 Onwards to Innovator.",
    likes: 224, comments: 47, celebrates: 142 },
  { id: "10", author: "Scope Connect", campus: "National HQ", time: "18h", type: "Weekly Winners",
    content: "This week's top 3 builders: Aarav (IIT Bombay), Diya (BITS Pilani), Kabir (VIT Vellore). +500 XP bonus dropped.",
    likes: 612, comments: 118, celebrates: 389 },
  { id: "11", author: "Scope Connect", campus: "National HQ", time: "20h", type: "Event Announced",
    content: "📅 Scope AI Weekend Sprint announced for May 9–10. 600 seats. Online + 6 campus hubs. RSVP now to lock your slot.",
    likes: 387, comments: 72, celebrates: 184 },
  { id: "12", author: "Tanvi Bose", campus: "St. Xavier's", time: "22h", type: "Builder Milestone",
    content: "First research paper accepted at the Scope Mental Health Report. Co-authored with 11 builders from 5 campuses 🧠",
    likes: 298, comments: 56, celebrates: 198 },
  { id: "13", author: "Aryan Verma", campus: "Jadavpur University", time: "1d", type: "Portfolio Spotlight",
    content: "Just published my campus podcast pilot — 14 minutes, 3 student founders, 1 honest conversation. Link in bio 🎙",
    likes: 142, comments: 38, celebrates: 64 },
  { id: "14", author: "Scope Connect", campus: "National HQ", time: "1d", type: "Challenge Launched",
    content: "📣 Open project seats filling fast: Climate Action Dashboard. 6 of 10 seats taken. Closes Friday.",
    likes: 234, comments: 41, celebrates: 87 },
  { id: "15", author: "Pooja Reddy", campus: "IIIT Hyderabad", time: "1d", type: "Project Launch",
    content: "Shipped my campus growth campaign. 1,400 new signups in 12 days for our chapter. Playbook in comments 👇",
    likes: 412, comments: 121, celebrates: 254 },
  { id: "16", author: "Founders Forum Manipal", campus: "Manipal University", time: "1d", type: "Campus Climbed Leaderboard",
    content: "Manipal climbed to top 7 chapters this month. Quiet, consistent shipping wins.",
    likes: 187, comments: 34, celebrates: 96 },
  { id: "17", author: "Ishaan Kapoor", campus: "DTU Delhi", time: "2d", type: "Achievement",
    content: "Officially Innovator-tier. Took 9 months, 14 projects and one really painful pivot. Worth it.",
    likes: 421, comments: 88, celebrates: 287 },
  { id: "18", author: "Scope Connect", campus: "National HQ", time: "2d", type: "Event Announced",
    content: "🎤 Founder AMA with Karan G. (Layerly, YC W25) on May 11. 600 seats. Bring your toughest questions.",
    likes: 532, comments: 142, celebrates: 314 },
  { id: "19", author: "Kabir Singh", campus: "VIT Vellore", time: "2d", type: "Project Launch",
    content: "Open-sourced our student resume analyzer. Trained on 4,200 anonymized CVs. Free for every Scope builder.",
    likes: 367, comments: 84, celebrates: 198 },
  { id: "20", author: "Scope Connect", campus: "National HQ", time: "3d", type: "Weekly Winners",
    content: "Builders are applying now — 184 applications across live challenges this week. Momentum is shifting.",
    likes: 298, comments: 47, celebrates: 156 },
  { id: "21", author: "Sneha Patil", campus: "Manipal University", time: "3d", type: "Builder Milestone",
    content: "Hit 100 days on Scope. Streak intact. Built 6 projects, joined 2 chapters, met 14 collaborators 🚀",
    likes: 234, comments: 56, celebrates: 167 },
  { id: "22", author: "Meera Nair", campus: "Manipal University", time: "3d", type: "Achievement",
    content: "Ambassador unlocked 🌟 Mentoring 8 new builders this cohort. Reach out if you want to chat product.",
    likes: 412, comments: 96, celebrates: 287 },
  { id: "23", author: "Scope Connect", campus: "National HQ", time: "4d", type: "Challenge Launched",
    content: "🎨 Design challenge: Scope Connect Mobile UI Pack. 5 seats, 5 weeks, founding designer credit.",
    likes: 367, comments: 84, celebrates: 198 },
  { id: "24", author: "Devansh Roy", campus: "Heritage Institute", time: "4d", type: "Portfolio Spotlight",
    content: "Added my first founder-track pitch to portfolio. Feedback brutal, learnings priceless.",
    likes: 142, comments: 28, celebrates: 73 },
  { id: "25", author: "Naina Choudhary", campus: "BITS Pilani", time: "5d", type: "Builder Milestone",
    content: "First brand partnership locked through a Scope opportunity. Marketing internship summer '26 secured.",
    likes: 287, comments: 64, celebrates: 187 },
  { id: "26", author: "Scope Connect", campus: "National HQ", time: "5d", type: "Campus Growth Milestone",
    content: "Kolkata zone added 4 new chapters this month. Eastern India is waking up 🔥",
    likes: 421, comments: 88, celebrates: 256 },
  { id: "27", author: "Karthik Subramanian", campus: "VIT Vellore", time: "5d", type: "Project Launch",
    content: "Built a campus events aggregator. Pulls from 18 student societies into one feed. Demo on my profile.",
    likes: 198, comments: 47, celebrates: 96 },
  { id: "28", author: "Scope Connect", campus: "National HQ", time: "6d", type: "Event Announced",
    content: "📚 Research Showcase on May 22 — 800 seats, mental health report drops live. Don't miss it.",
    likes: 256, comments: 41, celebrates: 124 },
  { id: "29", author: "Avni Sharma", campus: "IIIT Hyderabad", time: "6d", type: "Portfolio Spotlight",
    content: "First illustration commission via Scope ✨ Fresh opportunities just dropped on /opportunities.",
    likes: 142, comments: 28, celebrates: 87 },
  { id: "30", author: "Scope Connect", campus: "National HQ", time: "6d", type: "Weekly Winners",
    content: "Top campus this week: Jadavpur University. +127 XP per active builder. Eastern India is shipping.",
    likes: 387, comments: 92, celebrates: 234 },
  { id: "31", author: "Yash Agarwal", campus: "IIT Bombay", time: "7d", type: "Achievement",
    content: "Submitted my first national research squad application. Felt scary, did it anyway.",
    likes: 187, comments: 41, celebrates: 124 },
  { id: "32", author: "Scope Connect", campus: "National HQ", time: "7d", type: "Challenge Launched",
    content: "💡 Scope Founder Track 2026 now accepting pitches. ₹2L incubation pool. 25 seats. 12-week sprint.",
    likes: 612, comments: 154, celebrates: 384 },
  { id: "33", author: "Mahi Banerjee", campus: "Amity Kolkata", time: "7d", type: "Builder Milestone",
    content: "Joined my first cross-campus team this week. Working with builders from 3 cities. This is the dream.",
    likes: 198, comments: 47, celebrates: 142 },
  { id: "34", author: "Aditya Pillai", campus: "IIT Bombay", time: "8d", type: "Project Launch",
    content: "Launched a founder pitch deck template kit. 12 slides, fully editable, free for Scope builders.",
    likes: 367, comments: 84, celebrates: 198 },
  { id: "35", author: "Scope Connect", campus: "National HQ", time: "8d", type: "Event Announced",
    content: "🏫 Kolkata Campus Sprint on May 18 at Jadavpur. 240 seats. Your next move starts here.",
    likes: 287, comments: 64, celebrates: 156 },
];

export const interestTags = [
  "AI",
  "Startup",
  "Design",
  "Marketing",
  "Coding",
  "Research",
  "Content",
  "Robotics",
  "Climate",
  "EdTech",
  "Web3",
  "Community",
];
